name: agdc
channels:
    - conda-forge
dependencies:
    - python=3
    - click>=6
    - setuptools>=23.0.0
    - matplotlib>=1.5.2
    - numexpr>=2.6.0
    - numpy>=1.11.1
    - scipy>=0.17.1
    - postgresql
    - psycopg2>=2.6.2
    - python-dateutil
    - pyyaml>=3.11
    - gdal
    - rasterio>=0.35.1
    - shapely
    - netcdf4>=1.2.4
    - xarray>=0.7.2
    - dask>=0.10.1
    - toolz>=0.8.0
    - pip:
        - cachetools
        - future>=0.15
        - jsonschema
        - pathlib
        - pypeg2
        - singledispatch
        - sqlalchemy
