name: agdc-v2
channels:
    - conda-forge
dependencies:
    - python=3
    - setuptools
    - click>=5
    - pathlib
    - pyyaml
    - sqlalchemy
    - python-dateutil
    - jsonschema
    - cachetools
    - singledispatch
    - postgresql
    - psycopg2>=2.6.2
    - bottleneck
# NUMERIC
    - numpy
    - rasterio>=1.0a5
    - gdal
    - netcdf4
    - xarray
    - dask
# DISTRIBUTED
    - distributed
# INTERACTIVE
    - matplotlib>=1.5
    - fiona
# ANALYTICS
    - numexpr>=2.6
    - scipy>=0.17
    - pyparsing
# PREP SCRIPTS
    - shapely
# EXTRA - INTERACTIVE
    - bokeh
    - holoviews>=1.6.2
    - cartopy
    - jupyter
    - notebook
    - ipython
    - jupyter_console
    - pip:
        - future>=0.15
        - pypeg2
        - git+git://github.com/data-cube/agdc-v2.git@datacube-1.1.17
