source_type: ls8_espa_scene
output_type: ls8_espa_albers

description: Landsat 8 ESPA products, 5000x5000 pixel 30m tiles in Conus Albers (EPSG:5070)

location: '/projectnb/landsat/datasets/AGDC/TILES/'
file_path_template: 'LS8_OLI_ESPA/h{tile_index[0]:02d}/v{tile_index[1]:02d}/LS8_OLI_LEDAPS_5070_h{tile_index[0]:02d}_v{tile_index[1]:02d}_{start_time}.nc'
global_attributes:
  title: Boston University Data Cube Landsat Surface Reflectance
  summary: Landsat 8 Operational Land Imager Analysis Ready data prepared by USGS
  source: Surface reflectance from LaSRC
  institution: Boston University
  instrument: TM
  cdm_data_type: Grid
  keywords: AU/GA,NASA/GSFC/SED/ESD/LANDSAT,REFLECTANCE,CDR,OLI,EARTH SCIENCE
  keywords_vocabulary: GCMD
  platform: LANDSAT-8
  processing_level: L2
  product_version: '2.0.0'
  product_suite: USGS Landsat
  project: BU
  coverage_content_type: physicalMeasurement
  references: http://dx.doi.org/10.3334/ORNLDAAC/1146
  license: https://creativecommons.org/licenses/by/4.0/
  naming_authority: gov.usgs
  acknowledgment: Landsat data is provided by the United States Geological Survey (USGS).

# WELD CONUS
# UL x/y: -2565600.0, 3314800.0
# Tile size: 5000 pixels
# Tiles: 32 horizontal 21 vertical
ingestion_bounds: # Specified in Storage CRS coordinates. Will expand to tile boundaries.
  left: -2565600.0
  bottom: 164800.0
  right: 2234400.0
  top: 3314800.0

storage:
  driver: NetCDF CF
  crs: EPSG:5070
  origin:
    x: -2565600.0
    y: 3314800.0
  tile_size:
    x: 150000.0
    y: -150000.0
  resolution:
    x: 30
    y: -30
  chunking:
    x: 200
    y: 200
    time: 1
  dimension_order: ['time', 'y', 'x']

measurements:
    - name: coastal_aerosol
      dtype: int16
      nodata: -9999
      resampling_method: nearest
      src_varname: 'sr_band1'
      zlib: True
      attrs:
          long_name: "Surface Reflectance 0.43-0.45 microns (Coastal Aerosol)"
          alias: "band_1"
    - name: blue
      dtype: int16
      nodata: -9999
      resampling_method: nearest
      src_varname: 'sr_band2'
      zlib: True
      attrs:
          long_name: "Surface Reflectance 0.45-0.51 microns (Blue)"
          alias: "band_2"
    - name: green
      dtype: int16
      nodata: -9999
      resampling_method: nearest
      src_varname: 'sr_band3'
      zlib: True
      attrs:
          long_name: "Surface Reflectance 0.53-0.59 microns (Green)"
          alias: "band_4"
    - name: red
      dtype: int16
      nodata: -9999
      resampling_method: nearest
      src_varname: 'sr_band4'
      zlib: True
      attrs:
          long_name: "Surface Reflectance 0.64-0.67 microns (Red)"
          alias: "band_4"
    - name: nir
      dtype: int16
      nodata: -9999
      resampling_method: nearest
      src_varname: 'sr_band5'
      zlib: True
      attrs:
          long_name: "Surface Reflectance 0.85-0.88 microns (Near Infrared)"
          alias: "band_5"
    - name: swir1
      dtype: int16
      nodata: -9999
      resampling_method: nearest
      src_varname: 'sr_band6'
      zlib: True
      attrs:
          long_name: "Surface Reflectance 1.57-1.65 microns (Short-wave Infrared)"
          alias: "band_6"
    - name: swir2
      dtype: int16
      nodata: -9999
      resampling_method: nearest
      src_varname: 'sr_band7'
      zlib: True
      attrs:
          long_name: "Surface Reflectance 2.11-2.29 microns (Short-wave Infrared)"
          alias: "band_7"
    - name: cf_mask
      dtype: int16
      nodata: 255
      resampling_method: nearest
      src_varname: 'cfmask'
      zlib: True
      attrs:
          long_name: "CFmask"
    - name: cf_mask_conf
      dtype: int16
      nodata: 255
      resampling_method: nearest
      src_varname: 'cfmask_conf'
      zlib: True
      attrs:
          long_name: "CFmask Cloud Confidence"
    - name: cloud
      dtype: int16
      nodata: 0
      resampling_method: nearest
      src_varname: 'sr_cloud'
      zlib: True
      attrs:
          long_name: "Cloud"
